### ISSUE TITLE
How to find more AI texts? (Portuguese)

### ISSUE THREAD

**Issue by Pallas13** [andresilvapimentel/Gotcha-GPT#2]
Hello, I am developing a project for the detection of texts made by humans or IA for Portuguese for my high school. A detection is based in classification of texts, with this is necessary more texts. But I only found for language English, try made my texts of IA but not have computer processing, money and more time for this.
I found your repo, view that have a corpus with IA/Human texts for Portuguese and English, how you build this corpus? You have tricks for search more corpus for IA detection in Portuguese language.

**Comment by andresilvapimentel** [comment]
We have built both Portuguese and English datasets by ourselves.
The Portuguese texts are in the compressed file data_port.zip

**Comment by andresilvapimentel** [comment]
You can build a large dataset of Portuguese texts using python with the following procedure:
1) upload a large text in the docx extension (do not use pdf file);
2) convert it to ASCII text file;
3) split the text file in paragraphs, saving each paragraph in separate ASCII text files; (it is possible to split the text in each three paragraphs and save three paragraphs in one text file)
4) you can record each text in a pandas data frame or in a docx file.

If you perform this procedure, you can build a large dataset of Portuguese texts (or any language).

**Comment by Pallas13** [comment]
I am build a model with texts of data_port.zip and essays of humans and a
smail corpus of IA texts maked by my. Have 0.90/90% precision in tests
data. Tranks by ticks.

**Comment by andresilvapimentel** [comment]
The ai texts are also in the compressed file data_port.zip

**Comment by Pallas13** [comment]
Yes, I used it too in train model.
