### ISSUE TITLE
RangeError in #Step 4

### ISSUE THREAD

**Issue by pedroandrepi** [andresilvapimentel/Gotcha-GPT#3]
When I upload a DOCX file (thesis), the notebook prints the error "RangeError: Maximum call stack size exceeded.", as follows:

![image](https://github.com/user-attachments/assets/533110a7-fe2c-48a0-abae-78450e241b3a)

**Comment by andresilvapimentel** [comment]
This code was not developed to upload large docx files. Please, see instructions that describe the limitations of the method. It is not an issue of upload only. It is also an issue of the featurization of the text file that uses GPT2 transformer model. This model allows only 1024 tokens (about 700 words, less than 2 pages). My suggestion is to split the manuscript in small files of 1 page. This is very easy to perform using python, for example. After doing that, you can upload as many docx files as you want and perform the detection.
I already did this using 800 files to classify the 800 texts as human- or AI-generated texts. It perfectly did the task with about 98% accuracy.

**Comment by andresilvapimentel** [comment]
You can increase the size of texts if you pay the openai license, however it is not a huge increase. See below.
The token limit for gpt-35-turbo is 4,096 tokens. The token limits for gpt-4 and gpt-4-32k are 8,192 and 32,768, respectively. 
I believe you could perform until about 25000 words or about 30 pages. However, I warn you about the increase of time to perform the task in this latter way. I think it is much faster to perform the detection as explained previously splitting the texts in smaller 1-page texts.
